### ISSUE TITLE
The way of referencing existing resources in harvester should work equally.

### ISSUE THREAD

**Issue by firecyberice** [rancher-sandbox/cluster-api-provider-harvester#6]
The ssh `KeyPair` needs to be in the desired vm namespace.
https://github.com/rancher-sandbox/cluster-api-provider-harvester/blob/07d0b61f34a8277c0b8eac620dcd52e757e14b5b/samples/kubeadm/example.yaml#L133

On the other side the used image can specify a namespace and the image name in the form `NAMESPACE/IMAGENAME`

https://github.com/rancher-sandbox/cluster-api-provider-harvester/blob/07d0b61f34a8277c0b8eac620dcd52e757e14b5b/README.md?plain=1#L96

**Comment by belgaied2** [comment]
@firecyberice you are absolutely right. The `sshKeyPair` should also offer the flexibility of choosing another namespace. I will work on that soon.

**Comment by belgaied2** [comment]
Fixed in [b807130](https://github.com/rancher-sandbox/cluster-api-provider-harvester/commit/b807130ca2b05abe8d8538e36a4fe17d354be28f). 

Now the behaviour for all of the following fields is that they will accept both <NAMESPACE>/<NAME> and <NAME> (the latter will use HarvesterCluster.Spec.TargetNamespace as a namespace.):
- harvestercluster.spec.loadBalancerConfig.ippool.vmnetwork
- harvestermachine.spec.sshKeyPair
- harvestermachine.spec.networks
- harvestermachine.spec.volumes.imageName

@firecyberice Please let me know if there is anything not working correctly.
And thank you for your contributions.
