### ISSUE TITLE
Use variable names for the vm counts like described in cluster-api

### ISSUE THREAD

**Issue by firecyberice** [rancher-sandbox/cluster-api-provider-harvester#7]
Please use the same environment variables like all other providers (or at least how they are named in clusterctl)
https://github.com/rancher-sandbox/cluster-api-provider-harvester/blob/07d0b61f34a8277c0b8eac620dcd52e757e14b5b/README.md?plain=1#L97-L98

While clusterctl uses this `clusterctl generate cluster --control-plane-machine-count --worker-machine-count`
and the variables are named like shown here: https://github.com/kubernetes-sigs/cluster-api/blob/f335f132714a49adfcd815512c5125d8891f29d6/docs/book/src/clusterctl/provider-contract.md?plain=1#L327-L328

**Comment by belgaied2** [comment]
Fixed in [b807130](https://github.com/rancher-sandbox/cluster-api-provider-harvester/commit/b807130ca2b05abe8d8538e36a4fe17d354be28f). 

Now the behaviour for all of the following fields is that they will accept both <NAMESPACE>/<NAME> and <NAME> (the latter will use HarvesterCluster.Spec.TargetNamespace as a namespace.):
- harvestercluster.spec.loadBalancerConfig.ippool.vmnetwork
- harvestermachine.spec.sshKeyPair
- harvestermachine.spec.networks
- harvestermachine.spec.volumes.imageName

@firecyberice Please let me know if there is anything not working correctly.
And thank you for your contributions.

**Comment by belgaied2** [comment]
Fixed in 1b50974bd0a40a1e375c87ee1ac2486183303587
